class OverseaFeedEmsAir < ActiveHash::Base
  self.data = [
    { price: 0, name: '---' },
    { price: 90, name: '貨物総重量1kg(EMSエア便)' },
    { price: 110, name: '貨物総重量2kg(EMSエア便)' },
    { price: 130, name: '貨物総重量3kg(EMSエア便)' },
    { price: 150, name: '貨物総重量4kg(EMSエア便)' },
    { price: 170, name: '貨物総重量5kg(EMSエア便)' },
    { price: 190, name: '貨物総重量6kg(EMSエア便)' },
    { price: 210, name: '貨物総重量7kg(EMSエア便)' },
    { price: 230, name: '貨物総重量8kg(EMSエア便)' },
    { price: 250, name: '貨物総重量9kg(EMSエア便)' },
    { price: 270, name: '貨物総重量10kg(EMSエア便)' },
    { price: 220, name: '貨物総重量11kg(EMSエア便)' },
    { price: 240, name: '貨物総重量12kg(EMSエア便)' },
    { price: 260, name: '貨物総重量13kg(EMSエア便)' },
    { price: 280, name: '貨物総重量14kg(EMSエア便)' },
    { price: 300, name: '貨物総重量15kg(EMSエア便)' },
    { price: 320, name: '貨物総重量16kg(EMSエア便)' },
    { price: 340, name: '貨物総重量17kg(EMSエア便)' },
    { price: 360, name: '貨物総重量18kg(EMSエア便)' },
    { price: 380, name: '貨物総重量19kg(EMSエア便)' },
    { price: 400, name: '貨物総重量20kg(EMSエア便)' },
    { price: 420, name: '貨物総重量21kg(EMSエア便)' },
    { price: 440, name: '貨物総重量22kg(EMSエア便)' },
    { price: 460, name: '貨物総重量23kg(EMSエア便)' },
    { price: 480, name: '貨物総重量24kg(EMSエア便)' },
    { price: 500, name: '貨物総重量25kg(EMSエア便)' },
    { price: 520, name: '貨物総重量26kg(EMSエア便)' },
    { price: 540, name: '貨物総重量27kg(EMSエア便)' },
    { price: 560, name: '貨物総重量28kg(EMSエア便)' },
    { price: 580, name: '貨物総重量29kg(EMSエア便)' },
    { price: 600, name: '貨物総重量30kg(EMSエア便)' }
  ]
end
