class OverseaFeedEmsShip < ActiveHash::Base
  self.data = [
    { price: 0, name: '---' },
    { price: 110, name: '貨物総重量1kg(EMS船便)' },
    { price: 62, name: '貨物総重量2kg(EMS船便)' },
    { price: 46, name: '貨物総重量3kg(EMS船便)' },
    { price: 38, name: '貨物総重量4kg(EMS船便)' },
    { price: 33, name: '貨物総重量5kg(EMS船便)' },
    { price: 30, name: '貨物総重量6kg(EMS船便)' },
    { price: 27, name: '貨物総重量7kg(EMS船便)' },
    { price: 26, name: '貨物総重量8kg(EMS船便)' },
    { price: 24, name: '貨物総重量9kg(EMS船便)' },
    { price: 23, name: '貨物総重量10kg(EMS船便)' },
    { price: 22, name: '貨物総重量11kg(EMS船便)' },
    { price: 22, name: '貨物総重量12kg(EMS船便)' },
    { price: 21, name: '貨物総重量13kg(EMS船便)' },
    { price: 20, name: '貨物総重量14kg(EMS船便)' },
    { price: 20, name: '貨物総重量15kg(EMS船便)' },
    { price: 19, name: '貨物総重量16kg(EMS船便)' },
    { price: 19, name: '貨物総重量17kg(EMS船便)' },
    { price: 19, name: '貨物総重量18kg(EMS船便)' },
    { price: 18, name: '貨物総重量19kg(EMS船便)' },
    { price: 18, name: '貨物総重量20kg(EMS船便)' },
    { price: 18, name: '貨物総重量21kg(EMS船便)' },
    { price: 18, name: '貨物総重量22kg(EMS船便)' },
    { price: 18, name: '貨物総重量23kg(EMS船便)' },
    { price: 18, name: '貨物総重量24kg(EMS船便)' },
    { price: 17, name: '貨物総重量25kg(EMS船便)' },
    { price: 17, name: '貨物総重量26kg(EMS船便)' },
    { price: 17, name: '貨物総重量27kg(EMS船便)' },
    { price: 17, name: '貨物総重量28kg(EMS船便)' },
    { price: 17, name: '貨物総重量29kg(EMS船便)' },
    { price: 17, name: '貨物総重量30kg(EMS船便)' }
  ]
end
